### ISSUE TITLE
overflow:hidden out-of-bounds content shows as onscreen if inside viewport

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/jquery.onscreen#14]
I noticed in ken16199 blocks inside ABS were completing despite not being visible. At first I tried attaching the `inview` handler to the `body` text, which seem to fix some cases, but not others. I then noticed that when `inview` fired and reported `visible=true`, `visiblePartX=both` and `visiblePartY=both` the `onscreen` property would actually be `false`. I've tracked down what I think is the source of the problem:

https://github.com/adaptlearning/jquery.onscreen/blob/master/jquery.onscreen.js#L150

`wasScrolledOver` is determined by vertical position only - presume it needs a horizontal check also?

**Comment by chris-steele** [comment]
@oliverfoster my friend, I think you're the keymaster and gatekeeper for this lib, any chance you could check over this?

**Comment by oliverfoster** [comment]
this would only be the case if the element had gone from above the top of the window to below the bottom of the window. i can't quite work out in theory why that would be the case. i'm not sure if a horizontal check is going to help?

**Comment by chris-steele** [comment]
Hmm is the issue that if `wasScrolledOver` is `false`, [L156](https://github.com/adaptlearning/jquery.onscreen/blob/master/jquery.onscreen.js#L156) returns and so `_measurePreviousState` is not updated?

**Comment by oliverfoster** [comment]
Can you test, it's an easy change if it is.

**Comment by chris-steele** [comment]
No that didn't solve it unfortunately, so I'm not sure where the problem is :/ I've put a simple demo of this [here](https://clients.kineo.com/chrissteele/mod/scorm/view.php?id=31). To replicate just scroll down to the ABS and past it (or choose a following component from PLP) and notice non-visible ABS blocks complete. If you have chance let me know what your thoughts are. One thing we can obviously do is just add an onscreen().onscreen check to inview handlers, but there's hopefully a better solution.

**Comment by oliverfoster** [comment]
I finally figured out what this is.
It's that the items in the ABS are onscreen, just in an overflow:hidden container.... which is not an easy thing to find or calculate.

**Comment by chris-steele** [comment]
@oliverfoster nice work!
