### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by billofrights** [adaptlearning/jquery.onscreen#29]
I see that most of the other Adapt Learning repos carry a GPL license; is it a deliberate choice for this (very handy) OnScreen tool to not carry a license?

**Comment by oliverfoster** [comment]
I just haven't added a license yet, it would probably need to be more permissive than GPL. 

This library is getting a bit old now, as native support for this is now included in newer browsers [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) but it does work wonderfully.

I think the version in the adapt_framework might be slightly newer so I'll make sure they're in sync.

**Comment by oliverfoster** [comment]
I've added a license. I hope that's permissive enough?

**Comment by billofrights** [comment]
Awesome — thanks, Oliver!
