### ISSUE TITLE
PLP not updating on slower browsers/devices due to loop expiring

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/jquery.onscreen#5]
The commit https://github.com/adaptlearning/adapt_framework/commit/6ddcf8d829f83cfa6a6a703288680cbe47124951 partly solved the issue by increasing the amount allowed for the script to take before timing out but on my testing iPad (2nd generation, iOS 6.1.3) the loop kept expiring and the inview events were only sometimes triggered on long pages.

I increased the timeout [here](https://github.com/adaptlearning/jquery.onscreen/blob/master/jquery.onscreen.js#L121) to 500ms and then 1000ms, each time getting more consistently successful results.

Eventually I tried commenting out the [check for the loop expiry](https://github.com/adaptlearning/jquery.onscreen/blob/master/jquery.onscreen.js#L128) and it worked 100% of the time however, I am aware that the loop in now continually running in the background which is impacting on performance.

**Comment by oliverfoster** [comment]
Can you describe the sequence of events to recreate the issue. It's bee a while since I looked at it before.

**Comment by andrewhosgood** [comment]
Load the page on a long article with a text/graphic component block at the top and sometimes the PLP doesn't increase. Scroll up and down the page and nothing updates it.

Interact with a question component and then when you scroll back to the text/graphic, the PLP goes up for that first block.

The issue was first noticed on an iPhone (5s) although we have been able to recreate it in the older iPad (2nd gen) and sometimes even Chrome on Mac.

**Comment by andrewhosgood** [comment]
I think this can now be closed :)
